controllersHome:
    resource: ../../src/ControllersHome/
    type: annotation

controllersDemainWeArt:
    resource: ../../src/ControllersDemainWeArt/
    type: annotation

controllersAdmin:
    resource: ../../src/ControllersAdmin/
    type: annotation